name: 'Fetch ORCID Record'
description: 'Fetch record with detailed publications and authors in ORCID'
author: sxlllslgh

branding:
  icon: 'award'
  color: 'green'

inputs:
  orcid-id:
    description: 'ORCID ID of researcher'
    required: true
  access-token:
    description: 'ORCID access token'
    required: true
    
outputs:
  record:
    description: 'JSON record'
    
runs:
  using: 'node20'
  main: 'index.js'
